range_xz = -5..5
range_y = -5..0

cmd = "";

cmd += "######################################\n"
cmd += "# Auto-generated by _generate_pos.rb\n"
cmd += "######################################\n"
for i in range_xz
    for j in range_y
        for k in range_xz
            cmd += "execute align xyz positioned ~#{i} ~#{j} ~#{k} "
            cmd += "unless block ~ ~ ~ #light_level_checker:mob_spawnable_in "
            cmd += "if block ~ ~1 ~ #light_level_checker:mob_spawnable_in "
            cmd += "run function light_level_checker:ight_check/check"
            cmd += "\n"
        end
    end
end
File.open("pos.mcfunction","w"){|f|
    f.write(cmd)
}